server:
  port: 8080

yandex:
  cloud:
    api-key: ${YANDEX_CLOUD_API_KEY}
    api-endpoint: ${YANDEX_CLOUD_API_ENDPOINT:https://translate.api.cloud.yandex.net/translate/v2}
    requests-limit: ${YANDEX_CLOUD_REQUESTS_LIMIT:20} # requests per second
    symbols-limit: ${YANDEX_CLOUD_SYMBOLS_LIMIT:1000000}

translation:
  service:
    threads: ${TRANSLATION_SERVICE_THREADS:10} # threads on pool, which make requests to Yandex.Cloud

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:translation-db}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    schemas:
      - translations
