server:
  port: 8080

yandex:
  cloud:
    api-key: ${YANDEX_CLOUD_API_KEY}
    api-endpoint: ${YANDEX_CLOUD_API_ENDPOINT}
    requests-limit: ${YANDEX_CLOUD_REQUESTS_LIMIT} # requests per second
    symbols-limit: ${YANDEX_CLOUD_SYMBOLS_LIMIT}

translation:
  service:
    threads: ${TRANSLATION_SERVICE_THREADS} # threads on pool, which make requests to Yandex.Cloud

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    schemas:
      - translations
