yandex:
  cloud:
    api-key: ${YANDEX_CLOUD_API_KEY}
    api-endpoint: ${YANDEX_CLOUD_API_ENDPOINT}
    limit: 20 # requests per second

translation:
  service:
    threads: 10 # threads on pool, which makes requests to Yandex.Cloud